// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-B7CQFAfjgwnomF8OJucaUiv7j_aU-kE',
    appId: '1:521238673553:web:3f6ed9e15dacbed98a2730',
    messagingSenderId: '521238673553',
    projectId: 'harmonyhub-fbcf3',
    authDomain: 'harmonyhub-fbcf3.firebaseapp.com',
    storageBucket: 'harmonyhub-fbcf3.appspot.com',
    measurementId: 'G-63BSFNZDTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGsJDdkdrs-NlGQRC6IrpIaIzQTX4KKXQ',
    appId: '1:521238673553:android:91d15fbfa2674f6d8a2730',
    messagingSenderId: '521238673553',
    projectId: 'harmonyhub-fbcf3',
    storageBucket: 'harmonyhub-fbcf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2t1EJpcthKVkM5cIIJoSMDOd6ee_fPCs',
    appId: '1:521238673553:ios:9d689bd8290bc9938a2730',
    messagingSenderId: '521238673553',
    projectId: 'harmonyhub-fbcf3',
    storageBucket: 'harmonyhub-fbcf3.appspot.com',
    iosBundleId: 'com.example.harmonyhubhest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2t1EJpcthKVkM5cIIJoSMDOd6ee_fPCs',
    appId: '1:521238673553:ios:9d689bd8290bc9938a2730',
    messagingSenderId: '521238673553',
    projectId: 'harmonyhub-fbcf3',
    storageBucket: 'harmonyhub-fbcf3.appspot.com',
    iosBundleId: 'com.example.harmonyhubhest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-B7CQFAfjgwnomF8OJucaUiv7j_aU-kE',
    appId: '1:521238673553:web:ba09db03ebcdff858a2730',
    messagingSenderId: '521238673553',
    projectId: 'harmonyhub-fbcf3',
    authDomain: 'harmonyhub-fbcf3.firebaseapp.com',
    storageBucket: 'harmonyhub-fbcf3.appspot.com',
    measurementId: 'G-WLQBBP8H8B',
  );
}
